Add Wintab-compatible device support on Windows applications
chrisd1100/libmatoya pull request #57
Opened 2022-04-05 16:17 UTC by Namaneo

This PR adds support for Wintab-compatible devices (mostly Wacom) in Windows applications.
* The support is optional and transparent: Windows applications will check if `Wintab32.dll` is installed on the system (which comes with the Wacom driver), and will fallback to WinInk if not.
* A call to `MTY_AppEnablePen` is still required to enable pen on an application, whether Wintab is available or not.
* New method `MTY_AppOverrideTabletControls` added: when enabled, extended tablet inputs (e.g. ExpressKeys) are overriden by the application and received as `MTY_EVENT_WINTAB` instead of executing the driver-configured macros.
* Z-axis is now exposed in `MTY_EVENT_PEN` when this data is available.
* Those changes also includes a minor adjustment on WinInk right click: the button up flag is now properly set.

2022-04-14 01:23 UTC, RonaldH requested changes

2022-04-14 01:23 UTC, RonaldH commented on src/matoya.h
> +	MTY_WINTAB_TYPE_RING   ///< The Wintab input comes from a TouchRing manipulation.
Always add a `,` on the last enum.

2022-04-14 01:23 UTC, RonaldH commented on src/windows/appw.c
> +			if (app)
Should this be `if (app && app->wintab)`

2022-04-14 01:23 UTC, RonaldH commented on src/windows/appw.c
> +			wintab_recreate(&app->wintab, app_get_main_hwnd(app));
Want to check app and wintab here as well?

2022-04-14 01:23 UTC, RonaldH commented on src/windows/wintab.c
> +	uint8_t controls = props.data[0];
```suggestion
		return;

	uint8_t controls = props.data[0];
```

2022-04-14 01:23 UTC, RonaldH commented on src/windows/wintab.c
> +	uint32_t current;
```suggestion
	uint32_t current = 0;
```

Always initialize.

2022-04-14 01:23 UTC, RonaldH commented on src/windows/wintab.c
> +		uint8_t functions = props.data[0];
```suggestion
			continue;

		uint8_t functions = props.data[0];
```

2022-04-14 01:23 UTC, RonaldH commented on src/windows/wintab.c
> +			wt.##func = (type)MTY_SOGetSymbol(wt.instance, "WT" #sym); \
```suggestion
			wt.##func = (type) MTY_SOGetSymbol(wt.instance, "WT" #sym); \
```

2022-04-19 09:54 UTC, Namaneo commented on src/windows/appw.c
> +			wintab_recreate(&app->wintab, app_get_main_hwnd(app));
I added a check for `app`, and if `app->wintab` is `NULL`, we still want to create the context (`wintab_destroy`, called inside `wintab_recreate`, is skipped in that case)

2022-04-21 08:47 UTC, Namaneo commented
Moved to:
* https://github.com/parsec-cloud/libmatoya/pull/4

2022-04-21 08:47 UTC, closed without merging